feat：增加星期几显示、增加湿度、风向级、空气指数、空气质量，更新说明
rxrw/daily_morning pull request #105
Opened 2022-08-28 05:23 UTC by ihaoxiansheng

1.增加星期几字段
2.增加湿度、风向级、空气指数、空气质量字段

2022-08-28 05:41 UTC, rxrw requested changes
下划线命名，脚本不喜欢驼峰..

2022-08-28 05:58 UTC, ihaoxiansheng reviewed
fix：字段驼峰改为下划线

2022-08-28 06:40 UTC, rxrw approved these changes
其实还有 UPGRADE.md 的空格。。

够用够用

2022-08-28 06:43 UTC, zdy123321 reviewed
非常好

2022-08-28 06:46 UTC, merged

2022-08-29 05:30 UTC, wc18729397331 commented
> 1.增加星期几字段 2.增加湿度、风向级、空气指数、空气质量字段